import os
import tkinter as tk
from tkinter import filedialog
from pydub import AudioSegment
import subprocess
import torch
import shutil

def select_audio_file():
    """Opens a window to select the audio file."""
    root = tk.Tk()
    root.withdraw()
    file_path = filedialog.askopenfilename(
        title="Seleziona il file audio",
        initialdir="music_input",  # Parte dalla cartella music_input
        filetypes=[("Audio Files", "*.mp3 *.wav *.flac")]
    )
    return file_path

def save_as_mp3(input_file, output_path):
    """Saves the separated audio file as an MP3 using pydub."""
    audio_segment = AudioSegment.from_file(input_file)
    audio_segment.export(output_path, format="mp3")

def choose_model():
    """Allows the user to select a model numerically."""
    models = {"1": "htdemucs", "2": "mdx_extra", "3": "light"}
    print("Choose the Demucs model:")
    print("1 - htdemucs (High quality, slower)")
    print("2 - mdx_extra (Good balance between quality and speed)")
    print("3 - light (Faster, lower quality)")
    
    while True:
        choice = input("Enter the model number (default: 1): ")
        if choice == "" or choice in models:
            return models.get(choice, "htdemucs")
        else:
            print("Invalid choice. Please try again.")

def separate_audio(input_file, base_output_folder="separated_audio"):
    """
    Separate tools from an audio file using Demucs and save separate tracks to dedicated folders.
    """
    if not os.path.exists(base_output_folder):
        os.makedirs(base_output_folder)
    
    vocals_folder = os.path.join(base_output_folder, "vocals")
    no_vocals_folder = os.path.join(base_output_folder, "no_vocals")
    
    # Create folders if they do not exist
    os.makedirs(vocals_folder, exist_ok=True)
    os.makedirs(no_vocals_folder, exist_ok=True)
    
    model = choose_model()
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    print(f"Separation in progress with model {model} on {device}...")
    
    try:
        subprocess.run([
            "demucs", "-n", model, "--two-stems", "vocals", "--out", base_output_folder, "--device", device, input_file
        ], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error during Demucs execution: {e}")
        return
    
    # File name without extension
    track_name = os.path.splitext(os.path.basename(input_file))[0]
    demucs_output_folder = os.path.join(base_output_folder, model, track_name)
    
    # Verify the existence of the generated folder
    if not os.path.exists(demucs_output_folder):
        print(f"Error: the folder '{demucs_output_folder}' was not found.")
        return
    
    # Paths of the separated files
    vocals_path = os.path.join(demucs_output_folder, "vocals.wav")
    no_vocals_path = os.path.join(demucs_output_folder, "no_vocals.wav")
    
    # Verify the existence of the separated files
    if os.path.exists(vocals_path) and os.path.exists(no_vocals_path):
        # Create the output file names
        vocals_output_path = os.path.join(vocals_folder, f"{track_name}_vocals.mp3")
        no_vocals_output_path = os.path.join(no_vocals_folder, f"{track_name}_no_vocals.mp3")
        
        # Convert and save the separated files as MP3
        save_as_mp3(vocals_path, vocals_output_path)
        save_as_mp3(no_vocals_path, no_vocals_output_path)
        
        print(f"File MP3 saved:")
        print(f"- Vocals: {vocals_output_path}")
        print(f"- No Vocals: {no_vocals_output_path}")
        
        # Remove the intermediate files (.wav)
        os.remove(vocals_path)
        os.remove(no_vocals_path)
        
        # Remove the temporary folder generated by Demucs
        shutil.rmtree(os.path.join(base_output_folder, model), ignore_errors=True)
        print("Temporary folder removed.")
    else:
        print("Error: the separated files were not found.")

if __name__ == "__main__":
    print("Select audio file to separate")
    input_audio = select_audio_file()
    
    if not input_audio:
        print("No file selected. Exit.")
    else:
        separate_audio(input_audio)